app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('gestion/', views.gestion, name='gestion'),
    path('gestion/<int:id>', views.gestion, name='gestion'),
    path('gestion/<int:id>', views.gestion, name='gestion'),
    path('gestion/<int:id>/<int:q>', views.gestion, name='gestion'),
    path('eliminar_cliente', views.eliminar_cliente, name='eliminar'),
    path('editar_cliente/<int:cliente_id>', views.editar_cliente, name='editar_cliente'),
]

turnero/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

class Servicio(models.Model):
    servicio = models.CharField(max_length=100)
    def __str__(self):
        return self.servicio

class Cliente(models.Model):
    class Categoria(models.TextChoices):
        ALTA = 'A','3ra Edad, Embarazadas, Discapacidad'
        MEDIA = 'B','Clientes corporativos'
        BAJA = 'C','Clientes personales'
    
    cedula = models.IntegerField()
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    prioridad = models.CharField(choices=Categoria.choices,default=Categoria.BAJA)
    ticket = models.CharField()

    def __str__(self):
        return f"Cliente: {self.cedula}, Servicio: {self.servicio}, Prioridad: {self.prioridad}, Ticket: {self.ticket}"
# Create your models here.

app/forms.py
from django import forms
from .models import Cliente, Servicio

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'
        exclude = ['ticket']
        widgets = {
            'cedula': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese la cédula'}),
            'servicio': forms.Select(attrs={'class': 'form-control'}),
            'prioridad': forms.Select(attrs={'class': 'form-control'}),
        }

app/views.py
import random
import string
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from .models import Servicio, Cliente
from .forms import ClienteForm

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('app:gestion')
        else:
            messages.error(request, 'Credenciales inválidas. Por favor, intenta de nuevo.')
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('app:login')

def gestion(request,id=None):
    servicios = Servicio.objects.all()
    clientes = None
    if id:
        clientes = Cliente.objects.filter(servicio=id).order_by('prioridad', 'id')
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente = form.save(commit=False)
            existe = Cliente.objects.filter(cedula=cliente.cedula).first()
            if existe:
                existe.servicio = cliente.servicio
                existe.prioridad = cliente.prioridad
                cliente = existe
            else:
                cliente.ticket = generar_ticket_unico(cliente)
            cliente.save()
    
    form = ClienteForm()
    return render(
        request,
        'servicio.html',
        {
            'servicios':servicios,
            'clientes':clientes,
            'form': form,  
        }
    )

def generar_ticket_unico(cliente):
    cedula = str(cliente.cedula)
    longitud = 4 
    combinacion = generar_combinacion_aleatoria(longitud)
    ticket = cedula[:2] + combinacion
    if len(Cliente.objects.filter(ticket = ticket)) != 0:
        ticket = generar_ticket_unico(cliente)
    return ticket

def eliminar_cliente(request):
    if request.method == 'POST':
        cliente_id = request.POST.get('cliente_id')
        if cliente_id:
            # Obtener el cliente a eliminar a partir de su ID
            cliente = get_object_or_404(Cliente, id=cliente_id)
            cliente.delete()
            return JsonResponse({'status': 'success', 'message': 'Cliente eliminado exitosamente.'})
        else:
            return JsonResponse({'status': 'error', 'message': 'ID del cliente no proporcionado.'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Método de solicitud no válido.'})
    
def generar_combinacion_aleatoria(longitud):
    caracteres = string.ascii_letters + string.digits
    combinacion = ''.join(random.choice(caracteres) for _ in range(longitud))
    return combinacion


def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    form = ClienteForm(instance=cliente)
    return render(request, 'editar_cliente.html', {'form': form, 'cliente': cliente})

app/templates/editar_cliente.html
<form id="formEditarCliente" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar cambios">
</form>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Turnero{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
        crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
    <nav>
        <!-- Aquí puedes agregar el contenido del navbar si lo tienes -->
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    <footer>
        <!-- Aquí puedes agregar el contenido del footer si lo tienes -->
    </footer>

    <!-- Scripts de Bootstrap y otros scripts que necesites -->
    <!-- Bootstrap core JavaScript-->
  <script src="{% static 'admin/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'admin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'admin/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" 
            crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" 
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" 
            crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" 
            integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" 
            crossorigin="anonymous">
    </script>
    
    {% block scripts %}{% endblock %}
    <!-- Aquí puedes agregar otros scripts personalizados o tu script de AJAX -->
</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-4 mx-auto caja">
        <h2>Iniciar sesión</h2>
        <form method="post">
            {% csrf_token %}
            <label for="username">Usuario:</label>
            <input type="text" id="username" name="username" required class="form-control"><br>
            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" required class="form-control"><br>
            <button type="submit" class="btn btn-info">Iniciar sesión</button>
        </form>
        {% if messages %}
        {% for message in messages %}
        <div class="mensaje">
            <p>{{ message }}</p>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

app/templates/servicio.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'css/servicios.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="row container-fluid">
        <div class="col-md-3 mx-auto sidebar">
            <div class="list-group 1">
                {% for servicio in servicios %}
                <a href="{{ servicio.id }}" class="list-group-item list-group-item-action servicio-link">{{ servicio }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 mx-auto caja">
            <h1>Cargar Cliente</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>
    <div class="row container-fluid 2" style="margin-top: 20px;">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cédula</th>
                    <th>Servicio</th>
                    <th>Prioridad</th>
                    <th>Ticket</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr>
                    <td>{{ cliente.id }}</td>
                    <td>{{ cliente.cedula }}</td>
                    <td>{{ cliente.servicio }}</td>
                    <td>{{ cliente.get_prioridad_display }}</td>
                    <td>{{ cliente.ticket }}</td>
                    <td>
                        <button class="btn btn-primary btn-sm btn-editar" data-cliente-id="{{ cliente.id }}">Editar</button>
                        <button class="btn btn-danger btn-sm btn-eliminar" data-cliente-id="{{ cliente.id }}">Eliminar</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade 3" id="modalEditarCliente" tabindex="-1" role="dialog" aria-labelledby="modalEditarClienteLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalEditarClienteLabel">Editar Cliente</h5>
            </div>
            <div class="modal-body">
              <form id="formEditarCliente" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="button" id="guardarCambios" class="btn btn-primary btn-sm">Guardar cambios</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    $(document).ready(function() {
        $(".btn-eliminar").click(function(event) {
            event.preventDefault();

            var csrfToken = getCookie('csrftoken');
            var clienteId = $(this).data("cliente-id");

            $.ajax({
                type: "POST",
                url: "{% url 'app:eliminar' %}",
                data: { cliente_id: clienteId },
                headers: { "X-CSRFToken": csrfToken }, 
                success: function(response) {
                    location.reload();
                },
                error: function(error) {
                    console.log(error);
                }
            });
        });
        $(".btn-editar").click(function(event) {
            event.preventDefault(); // Evitar el comportamiento predeterminado del botón
      
            var clienteId = $(this).data("cliente-id");
            var url = "{% url 'app:editar_cliente' 0 %}".replace('0', clienteId);
      
            // Realizar una solicitud AJAX para obtener el formulario de edición
            $.get(url, function(response) {
              // Insertar el formulario en el cuerpo del modal
              $("#modalEditarCliente .modal-body").html(response);
      
              // Mostrar el modal
              $("#modalEditarCliente").modal("show");
            });
        });
    });
</script>
{% endblock %}